/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about: () => import("@/views/about/index.vue"),
  detection_datasource: () => import("@/views/detection/datasource/index.vue"),
  "detection_event-type": () => import("@/views/detection/event-type/index.vue"),
  detection_protocol: () => import("@/views/detection/protocol/index.vue"),
  detection_rule: () => import("@/views/detection/rule/index.vue"),
  detection_task: () => import("@/views/detection/task/index.vue"),
  event_attck: () => import("@/views/event/attck/index.vue"),
  "event_event-list": () => import("@/views/event/event-list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  manage: () => import("@/views/manage/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
