/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 100
    }
  },
  {
    name: 'detection',
    path: '/detection',
    component: 'layout.base',
    meta: {
      title: 'detection',
      i18nKey: 'route.detection',
      icon: 'carbon:ibm-cloud-security-compliance-center-workload-protection',
      order: 11
    },
    children: [
      {
        name: 'detection_datasource',
        path: '/detection/datasource',
        component: 'view.detection_datasource',
        meta: {
          title: 'detection_datasource',
          i18nKey: 'route.detection_datasource',
          icon: 'material-symbols:database',
          order: 5
        }
      },
      {
        name: 'detection_event-type',
        path: '/detection/event-type',
        component: 'view.detection_event-type',
        meta: {
          title: 'detection_event-type',
          i18nKey: 'route.detection_event-type',
          icon: 'carbon:category',
          order: 3
        }
      },
      {
        name: 'detection_protocol',
        path: '/detection/protocol',
        component: 'view.detection_protocol',
        meta: {
          title: 'detection_protocol',
          i18nKey: 'route.detection_protocol',
          icon: 'tabler:protocol',
          order: 4
        }
      },
      {
        name: 'detection_rule',
        path: '/detection/rule',
        component: 'view.detection_rule',
        meta: {
          title: 'detection_rule',
          i18nKey: 'route.detection_rule',
          icon: 'carbon:rule-draft',
          order: 2
        }
      },
      {
        name: 'detection_task',
        path: '/detection/task',
        component: 'view.detection_task',
        meta: {
          title: 'detection_task',
          i18nKey: 'route.detection_task',
          icon: 'oui:ml-outlier-detection-job',
          order: 1
        }
      }
    ]
  },
  {
    name: 'event',
    path: '/event',
    component: 'layout.base',
    meta: {
      title: 'event',
      i18nKey: 'route.event',
      icon: 'solar:bill-list-outline',
      order: 12
    },
    children: [
      {
        name: 'event_attck',
        path: '/event/attck',
        component: 'view.event_attck',
        meta: {
          title: 'event_attck',
          i18nKey: 'route.event_attck',
          icon: 'maki:library-15',
          order: 2
        }
      },
      {
        name: 'event_event-list',
        path: '/event/event-list',
        component: 'view.event_event-list',
        meta: {
          title: 'event_event-list',
          i18nKey: 'route.event_event-list',
          icon: 'material-symbols:data-alert',
          order: 1
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base$view.manage',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      order: 90,
      roles: ['R_ADMIN']
    }
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
